name: Deploy Angular App to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install dependencies in frontend
      - name: Install dependencies
        run: npm ci
        working-directory: frontend

      # Build Angular app (production) in frontend
      - name: Build Angular app
        run: npm run build -- --configuration production
        working-directory: frontend

      # Deploy to Firebase Hosting using frontend config
      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@v13.23.0
        with:
          args: deploy --only hosting
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
